import createClient from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript
import { useMiddleware } from "./useMiddleware";

// Создаем middleware с помощью хука
const { createMiddleware } = useMiddleware();

// Создаем клиент с базовым URL для dev сервера
export const client = createClient<paths>({ 
    baseUrl: "https://dev.vardek.online",
});

// Регистрируем middleware 
client.use(createMiddleware());