import createClient from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript
import { useMiddleware } from "./useMiddleware";
import { BASE_DOMAIN } from "@/utils/originalDomain";

// Создаем middleware с помощью хука
const { createMiddleware } = useMiddleware();

// Создаем клиент с базовым URL для dev сервера
export const client = createClient<paths>({
    baseUrl: `https://${BASE_DOMAIN}`,
});

// Регистрируем middleware 
client.use(createMiddleware());
