import createClient, { Middleware } from "openapi-fetch";
import type { paths } from "./schema"; // generated by openapi-typescript

const rootMiddleware: Middleware = {
    async onRequest({ request, options }) {
        //request.headers.set("foo", "bar");
        return request;
    },

    async onResponse({ request, response, }) {
        return response;
    },

    async onError({ error }) {
        // wrap errors thrown by fetch
        console.error(error);
        throw new Error("Oops, fetch failed");
    },
  };
  


export const client = createClient<paths>({ 
    baseUrl: "https://api.dev/v1/",
    //TODO: add headers
    // headers: {
    //     "Content-Type": "application/json",
    // },
});

// register middleware
client.use(rootMiddleware);